SoojiK.CS5600.LearnC: SoojiK.CS5600.LearnC.o mpg2km.o
	clang -o SoojiK.CS5600.LearnC SoojiK.CS5600.LearnC.o mpg2km.o

SoojiK.CS5600.LearnC.o: SoojiK.CS5600.LearnC.c mpg2km.h
	clang -c SoojiK.CS5600.LearnC.c

mpg2km.o: mpg2km.c mpg2km.h
	clang -c mpg2km.c

clean:
	rm -f SoojiK.CS5600.LearnC SoojiK.CS5600.LearnC.o mpg2km.o
